baseURL = 'https://jonathan-kaplan.eu/'

copyright = "© 2025 Jonathan Kaplan"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Paris"
timeout = "120s"

[markup.goldmark.renderer]
  unsafe = true

[params]
  defaultTheme = "dark"
  description = "Jonathan Kaplan's Online Gallery"
  title = "My Gallery"
  [params.author]
    email = "github@jonathan-kaplan.eu"
    name = "Jonathan Kaplan"
  [params.socialIcons]
    email = "/contact"
    #website = "https://example.com"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "gallery"

[menu]
  [[menu.footer]]
#   name = "Github"
#   url = "https://github.com/nicokaiser/hugo-theme-gallery/"
#   weight = 3

[services]
  [services.rss]
    limit = 100
    
[languages]
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    title = 'Jonathan Kaplan Photographer'
    weight = 1
      [languages.en.params]
        description = "Film photography (analog) is the main medium Jonathan uses. This website showcases work primarily in black & white. Please read **[about](about)** the reproductions of photographs shown on this website and the **[copyright notice](copyright)**"
        [languages.en.params.socialIcons]
          email = "/contact"
  [languages.fr]
    languageCode = 'fr'
    languageName = 'Français'
    title = 'Jonathan Kaplan Photographe'
    weight = 2
      [languages.fr.params]
        description = "La photographie argentique (analogique) est le principal médium utilisé par Jonathan. Ce site web présente principalement des œuvres en noir et blanc. Veuillez lire **[à propos](about)** des reproductions des photographies présentées sur ce site ainsi que la **[notice de droit d'auteur](copyright)**."
        [languages.fr.params.socialIcons]
          email = "/fr/contact"

